### ISSUE TITLE
Please add version number tags 

### ISSUE THREAD

**Issue by bramton** [mteg/braa#5]
Could you please add a `0.82` tag to the initial commit ? And also add the `0.9` tag to the 7a5bc2f commit ? I noticed that this commit show 0.9 in the print help function.

These small changes will make the life of people creating binary packages a lot easier.

**Comment by mteg** [comment]
Done, see: https://github.com/mteg/braa/tags

Let me know if this works!

**Comment by diizzyy** [comment]
It works but versioning is now going backwards as last release was 0.82 and new is 0.9.1 instead of 0.91?
It's not the end of the world though...

**Comment by bramton** [comment]
Thanks for the prompt response and action. Much appreciated. I hope starting with 0.9.1 the version naming will remain consistent, otherwise packagers will have nightmares  :wink:

**Comment by mteg** [comment]
The "floating point" versioning scheme (0.82 being a 0.02 improvement over 0.8) comes straight from 2003. I don't even know if semantic versioning was around, but I sure hadn't heard about it back then... Anyway, it's high time to get it straight. Closing.
